service: whhc-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-sentry

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

custom:
  serverless-offline:
    port: 4000
  sentry:
    dsn: ${env:SENTRY_DNS}
  webpack:
    packager: 'yarn'
    includeModules: false
    keepOutputDirectory: true

package:
  individually: true

functions:
  gocardless:
    handler: src/functions/webhook-gocardless.handler
    events:
      - http:
          method: post
          path: webhooks/gocardless
