service: whhc-api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-sentry

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

custom:
  serverless-offline:
    port: 4000
  sentry:
    dsn: ${env:SENTRY_DNS}
  webpack:
    packager: 'yarn'

package:
  individually: true

functions:
  cron-similar-news:
    handler: src/functions/cron-similar-news.handler
    memorySize: 1024
    timeout: 30
    events:
      - schedule:
          name: cron-similar-news-${opt:stage, 'dev'}
          rate: cron(0 2 ? * * *)
  webhook-contentful:
    handler: src/functions/webhook-contentful.handler
    events:
      - http:
          method: post
          path: webhooks/contentful
  webhook-gocardless:
    handler: src/functions/webhook-gocardless.handler
    events:
      - http:
          method: post
          path: webhooks/gocardless
